# Generated by Django 2.2.4 on 2019-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(help_text='Transaction product', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_product', to='transactions.Product'),
        ),
    ]
